import { Field } from "../interfaces"

export const fields:Field[] = [
    {
        name: "Freies Parkieren",
        street: "",
        id: 0,
        row: 0,
        width: 2,
        height: 2,
        orientation: "bottom",
        boardNumber: 20,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: true,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Winterthur",
        street: "Bahnhofplatz",
        id: 1,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 21,
        isProperty: true,
        propertyColor: "red",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Chance",
        street: "",
        id: 2,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 22,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: true,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "none",
    },
    {
        name: "St. Gallen",
        street: "Marktplatz",
        id: 3,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 23,
        isProperty: true,
        propertyColor: "red",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Bern",
        street: "Bundesplatz",
        id: 4,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 24,
        isProperty: true,
        propertyColor: "red",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Überlandbahnen",
        street: "",
        id: 5,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 25,
        isProperty: false,
        propertyColor: "",
        isTrain: true,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Luzern",
        street: "Weggisplatz",
        id: 6,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 26,
        isProperty: true,
        propertyColor: "yellow",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Zürich",
        street: "Rennweg",
        id: 7,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 27,
        isProperty: true,
        propertyColor: "yellow",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Wasserwerke",
        street: "",
        id: 8,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 28,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: true,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Lausanne",
        street: "Rue de Bourg",
        id: 9,
        row: 0,
        width: 1,
        height: 2,
        orientation: "bottom",
        boardNumber: 29,
        isProperty: true,
        propertyColor: "yellow",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Polizei",
        street: "",
        id: 10,
        row: 0,
        width: 2,
        height: 2,
        orientation: "bottom",
        boardNumber: 30,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: true,
        isSpacer: false,
        icon: "",
    },
    {
        name: "La-Chaux-de-Fonds",
        street: "Rue Leop. Robert",
        id: 11,
        row: 1,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 19,
        isProperty: true,
        propertyColor: "orange",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "",
        street: "",
        id: 12,
        row: 1,
        width: 10,
        height: 1,
        orientation: "right",
        boardNumber: 999,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: true,
        icon: "",
    },
    {
        name: "Basel",
        street: "Freiestrasse",
        id: 13,
        row: 1,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 31,
        isProperty: true,
        propertyColor: "green",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Freiburg",
        street: "Bahnhofstrasse",
        id: 14,
        row: 2,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 18,
        isProperty: true,
        propertyColor: "orange",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Genf",
        street: "Rue de la Croix d'Or",
        id: 16,
        row: 2,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 32,
        isProperty: true,
        propertyColor: "green",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Kanzlei",
        street: "",
        id: 17,
        row: 3,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 17,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: true,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Kanzlei",
        street: "",
        id: 19,
        row: 3,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 33,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: true,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Biel",
        street: "Nidaugasse",
        id: 20,
        row: 4,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 16,
        isProperty: true,
        propertyColor: "orange",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Bern",
        street: "Spitalgasse",
        id: 22,
        row: 4,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 34,
        isProperty: true,
        propertyColor: "green",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Vereinigte Bergbahnen",
        street: "",
        id: 23,
        row: 5,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 15,
        isProperty: false,
        propertyColor: "",
        isTrain: true,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Vereinigte Schwebebahnen",
        street: "",
        id: 26,
        row: 5,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 35,
        isProperty: false,
        propertyColor: "",
        isTrain: true,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Lugano",
        street: "Via Nassa",
        id: 27,
        row: 6,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 14,
        isProperty: true,
        propertyColor: "purple",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Chance",
        street: "",
        id: 29,
        row: 6,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 36,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: true,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Solothurn",
        street: "Hauptgasse",
        id: 30,
        row: 7,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 13,
        isProperty: true,
        propertyColor: "purple",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Lausanne",
        street: "Place St. Francois",
        id: 32,
        row: 7,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 37,
        isProperty: true,
        propertyColor: "blue",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Elektrizitätswerke",
        street: "",
        id: 33,
        row: 8,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 12,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: true,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Nachsteuer",
        street: "",
        id: 35,
        row: 8,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 38,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: true,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Basel",
        street: "Steinen-Vorstadt",
        id: 36,
        row: 9,
        width: 2,
        height: 1,
        orientation: "right",
        boardNumber: 11,
        isProperty: true,
        propertyColor: "purple",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Zürich",
        street: "Paradeplatz",
        id: 38,
        row: 9,
        width: 2,
        height: 1,
        orientation: "left",
        boardNumber: 39,
        isProperty: true,
        propertyColor: "blue",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Gefängnis",
        street: "",
        id: 39,
        row: 10,
        width: 2,
        height: 2,
        orientation: "top",
        boardNumber: 10,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: true,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Thun",
        street: "Hauptgasse",
        id: 40,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 9,
        isProperty: true,
        propertyColor: "lightblue",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Neuenburg",
        street: "Place Purry",
        id: 41,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 8,
        isProperty: true,
        propertyColor: "lightblue",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Chance",
        street: "",
        id: 42,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 7,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: true,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Aarau",
        street: "Rathausplatz",
        id: 43,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 6,
        isProperty: true,
        propertyColor: "lightblue",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Vereinigte Privatbahnen",
        street: "",
        id: 44,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 5,
        isProperty: false,
        propertyColor: "",
        isTrain: true,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Einkommenssteuer",
        street: "",
        id: 45,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 4,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: true,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Schaffhausen",
        street: "Vordergasse",
        id: 46,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 3,
        isProperty: true,
        propertyColor: "brown",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Kanzlei",
        street: "",
        id: 47,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 2,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: true,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Chur",
        street: "Kornplatz",
        id: 48,
        row: 10,
        width: 2,
        height: 1,
        orientation: "top",
        boardNumber: 1,
        isProperty: true,
        propertyColor: "brown",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: false,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
    {
        name: "Start",
        street: "",
        id: 49,
        row: 10,
        width: 2,
        height: 2,
        orientation: "top",
        boardNumber: 0,
        isProperty: false,
        propertyColor: "",
        isTrain: false,
        isUtility: false,
        isChance: false,
        isKanzlei: false,
        isEvent: false,
        isGo: true,
        isJail: false,
        isParking: false,
        isPopo: false,
        isSpacer: false,
        icon: "",
    },
]